[workspace]
resolver = "2"

members = [
    "ruwm",
    "ruwm-esp32",
]

exclude = ["ruwm-web", "ruwm-sim"]

[patch.crates-io]
yewdux-middleware = { git = "https://github.com/ivmarkov/yewdux-middleware" }
hal-sim = { git = "https://github.com/ivmarkov/hal-sim" }
edge-frame = { git = "https://github.com/ivmarkov/edge-frame" }
gfx-xtra = { git = "https://github.com/ivmarkov/gfx-xtra" }
ssd1351 = { git = "https://github.com/ivmarkov/ssd1351" }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"
