[workspace]
resolver = "2"

members = [
    "ruwm",
    "ruwm-esp32",
]

exclude = ["ruwm-web", "ruwm-sim"]

[patch.crates-io]
#socket2 = { git = "https://github.com/esp-rs-compat/socket2" }
#polling = { git = "https://github.com/esp-rs-compat/polling" }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"
