[workspace]
resolver = "2"

members = [
    "ruwm",
    "ruwm-esp32",
]

exclude = ["ruwm-web", "ruwm-sim"]

[patch.crates-io]
edge-executor = { git = "https://github.com/ivmarkov/edge-executor" }
crossbeam-utils = { git = "https://github.com/crossbeam-rs/crossbeam" }
heapless = { git = "https://github.com/rust-embedded/heapless" }
ssd1351 = { git = "https://github.com/ivmarkov/ssd1351" }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"
